### ISSUE TITLE
Delay and jitter

### ISSUE THREAD

**Issue by afsheen07** [3xpl01tc0d3r/Callidus#1]
Hi,

Is there an easy way to implement a delay and jitter percentage to how often the Outlook client beacons out to check if there's a command?

Also, is it neccesary to run Auth() every time in the RunAsync() method? Is there a way we can only auth once and preserve it?

**Comment by 3xpl01tc0d3r** [comment]
To add delay you can modify the Thread.Sleep() function in the code. Currently you cannot change it dynamically.
https://github.com/3xpl01tc0d3r/Callidus/blob/master/OutlookC2Client/Program.cs#L87

Ideally RunAsync() function will only be called when the program starts.
